/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangRegisterRouteImport } from './routes/$lang/register'
import { Route as LangSubscribeRouteRouteImport } from './routes/$lang/subscribe/route'
import { Route as LangStudentRouteRouteImport } from './routes/$lang/student/route'
import { Route as LangDashboardRouteRouteImport } from './routes/$lang/dashboard/route'
import { Route as LangSubscribeIndexRouteImport } from './routes/$lang/subscribe/index'
import { Route as LangStudentIndexRouteImport } from './routes/$lang/student/index'
import { Route as LangDashboardIndexRouteImport } from './routes/$lang/dashboard/index'
import { Route as LangTeacherTeacherSlugRouteImport } from './routes/$lang/teacher/$teacherSlug'
import { Route as LangSubscribeCheckoutRouteImport } from './routes/$lang/subscribe/checkout'
import { Route as LangCourseCourseSlugRouteImport } from './routes/$lang/course/$courseSlug'
import { Route as LangStudentCoursesIndexRouteImport } from './routes/$lang/student/courses/index'
import { Route as LangStudentAssignmentsIndexRouteImport } from './routes/$lang/student/assignments/index'
import { Route as LangDashboardStudentsIndexRouteImport } from './routes/$lang/dashboard/students/index'
import { Route as LangDashboardSettingsIndexRouteImport } from './routes/$lang/dashboard/settings/index'
import { Route as LangDashboardPaymentsIndexRouteImport } from './routes/$lang/dashboard/payments/index'
import { Route as LangDashboardCoursesIndexRouteImport } from './routes/$lang/dashboard/courses/index'
import { Route as LangDashboardAssignmentsIndexRouteImport } from './routes/$lang/dashboard/assignments/index'
import { Route as LangDashboardCoursesNewRouteImport } from './routes/$lang/dashboard/courses/new'
import { Route as LangStudentCoursesCourseIdIndexRouteImport } from './routes/$lang/student/courses/$courseId/index'
import { Route as LangDashboardCoursesCourseIdLessonsIndexRouteImport } from './routes/$lang/dashboard/courses/$courseId/lessons/index'
import { Route as LangStudentCoursesCourseIdLessonsLessonIdRouteImport } from './routes/$lang/student/courses/$courseId/lessons/$lessonId'
import { Route as LangDashboardCoursesCourseIdLessonsNewRouteImport } from './routes/$lang/dashboard/courses/$courseId/lessons/new'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangRegisterRoute = LangRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSubscribeRouteRoute = LangSubscribeRouteRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangStudentRouteRoute = LangStudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDashboardRouteRoute = LangDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSubscribeIndexRoute = LangSubscribeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangSubscribeRouteRoute,
} as any)
const LangStudentIndexRoute = LangStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangStudentRouteRoute,
} as any)
const LangDashboardIndexRoute = LangDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangDashboardRouteRoute,
} as any)
const LangTeacherTeacherSlugRoute = LangTeacherTeacherSlugRouteImport.update({
  id: '/teacher/$teacherSlug',
  path: '/teacher/$teacherSlug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSubscribeCheckoutRoute = LangSubscribeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LangSubscribeRouteRoute,
} as any)
const LangCourseCourseSlugRoute = LangCourseCourseSlugRouteImport.update({
  id: '/course/$courseSlug',
  path: '/course/$courseSlug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangStudentCoursesIndexRoute = LangStudentCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => LangStudentRouteRoute,
} as any)
const LangStudentAssignmentsIndexRoute =
  LangStudentAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => LangStudentRouteRoute,
  } as any)
const LangDashboardStudentsIndexRoute =
  LangDashboardStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)
const LangDashboardSettingsIndexRoute =
  LangDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)
const LangDashboardPaymentsIndexRoute =
  LangDashboardPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)
const LangDashboardCoursesIndexRoute =
  LangDashboardCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)
const LangDashboardAssignmentsIndexRoute =
  LangDashboardAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)
const LangDashboardCoursesNewRoute = LangDashboardCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => LangDashboardRouteRoute,
} as any)
const LangStudentCoursesCourseIdIndexRoute =
  LangStudentCoursesCourseIdIndexRouteImport.update({
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => LangStudentRouteRoute,
  } as any)
const LangDashboardCoursesCourseIdLessonsIndexRoute =
  LangDashboardCoursesCourseIdLessonsIndexRouteImport.update({
    id: '/courses/$courseId/lessons/',
    path: '/courses/$courseId/lessons/',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)
const LangStudentCoursesCourseIdLessonsLessonIdRoute =
  LangStudentCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/courses/$courseId/lessons/$lessonId',
    path: '/courses/$courseId/lessons/$lessonId',
    getParentRoute: () => LangStudentRouteRoute,
  } as any)
const LangDashboardCoursesCourseIdLessonsNewRoute =
  LangDashboardCoursesCourseIdLessonsNewRouteImport.update({
    id: '/courses/$courseId/lessons/new',
    path: '/courses/$courseId/lessons/new',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/dashboard': typeof LangDashboardRouteRouteWithChildren
  '/$lang/student': typeof LangStudentRouteRouteWithChildren
  '/$lang/subscribe': typeof LangSubscribeRouteRouteWithChildren
  '/$lang/register': typeof LangRegisterRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/course/$courseSlug': typeof LangCourseCourseSlugRoute
  '/$lang/subscribe/checkout': typeof LangSubscribeCheckoutRoute
  '/$lang/teacher/$teacherSlug': typeof LangTeacherTeacherSlugRoute
  '/$lang/dashboard/': typeof LangDashboardIndexRoute
  '/$lang/student/': typeof LangStudentIndexRoute
  '/$lang/subscribe/': typeof LangSubscribeIndexRoute
  '/$lang/dashboard/courses/new': typeof LangDashboardCoursesNewRoute
  '/$lang/dashboard/assignments/': typeof LangDashboardAssignmentsIndexRoute
  '/$lang/dashboard/courses/': typeof LangDashboardCoursesIndexRoute
  '/$lang/dashboard/payments/': typeof LangDashboardPaymentsIndexRoute
  '/$lang/dashboard/settings/': typeof LangDashboardSettingsIndexRoute
  '/$lang/dashboard/students/': typeof LangDashboardStudentsIndexRoute
  '/$lang/student/assignments/': typeof LangStudentAssignmentsIndexRoute
  '/$lang/student/courses/': typeof LangStudentCoursesIndexRoute
  '/$lang/student/courses/$courseId/': typeof LangStudentCoursesCourseIdIndexRoute
  '/$lang/dashboard/courses/$courseId/lessons/new': typeof LangDashboardCoursesCourseIdLessonsNewRoute
  '/$lang/student/courses/$courseId/lessons/$lessonId': typeof LangStudentCoursesCourseIdLessonsLessonIdRoute
  '/$lang/dashboard/courses/$courseId/lessons/': typeof LangDashboardCoursesCourseIdLessonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/register': typeof LangRegisterRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/course/$courseSlug': typeof LangCourseCourseSlugRoute
  '/$lang/subscribe/checkout': typeof LangSubscribeCheckoutRoute
  '/$lang/teacher/$teacherSlug': typeof LangTeacherTeacherSlugRoute
  '/$lang/dashboard': typeof LangDashboardIndexRoute
  '/$lang/student': typeof LangStudentIndexRoute
  '/$lang/subscribe': typeof LangSubscribeIndexRoute
  '/$lang/dashboard/courses/new': typeof LangDashboardCoursesNewRoute
  '/$lang/dashboard/assignments': typeof LangDashboardAssignmentsIndexRoute
  '/$lang/dashboard/courses': typeof LangDashboardCoursesIndexRoute
  '/$lang/dashboard/payments': typeof LangDashboardPaymentsIndexRoute
  '/$lang/dashboard/settings': typeof LangDashboardSettingsIndexRoute
  '/$lang/dashboard/students': typeof LangDashboardStudentsIndexRoute
  '/$lang/student/assignments': typeof LangStudentAssignmentsIndexRoute
  '/$lang/student/courses': typeof LangStudentCoursesIndexRoute
  '/$lang/student/courses/$courseId': typeof LangStudentCoursesCourseIdIndexRoute
  '/$lang/dashboard/courses/$courseId/lessons/new': typeof LangDashboardCoursesCourseIdLessonsNewRoute
  '/$lang/student/courses/$courseId/lessons/$lessonId': typeof LangStudentCoursesCourseIdLessonsLessonIdRoute
  '/$lang/dashboard/courses/$courseId/lessons': typeof LangDashboardCoursesCourseIdLessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/dashboard': typeof LangDashboardRouteRouteWithChildren
  '/$lang/student': typeof LangStudentRouteRouteWithChildren
  '/$lang/subscribe': typeof LangSubscribeRouteRouteWithChildren
  '/$lang/register': typeof LangRegisterRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/course/$courseSlug': typeof LangCourseCourseSlugRoute
  '/$lang/subscribe/checkout': typeof LangSubscribeCheckoutRoute
  '/$lang/teacher/$teacherSlug': typeof LangTeacherTeacherSlugRoute
  '/$lang/dashboard/': typeof LangDashboardIndexRoute
  '/$lang/student/': typeof LangStudentIndexRoute
  '/$lang/subscribe/': typeof LangSubscribeIndexRoute
  '/$lang/dashboard/courses/new': typeof LangDashboardCoursesNewRoute
  '/$lang/dashboard/assignments/': typeof LangDashboardAssignmentsIndexRoute
  '/$lang/dashboard/courses/': typeof LangDashboardCoursesIndexRoute
  '/$lang/dashboard/payments/': typeof LangDashboardPaymentsIndexRoute
  '/$lang/dashboard/settings/': typeof LangDashboardSettingsIndexRoute
  '/$lang/dashboard/students/': typeof LangDashboardStudentsIndexRoute
  '/$lang/student/assignments/': typeof LangStudentAssignmentsIndexRoute
  '/$lang/student/courses/': typeof LangStudentCoursesIndexRoute
  '/$lang/student/courses/$courseId/': typeof LangStudentCoursesCourseIdIndexRoute
  '/$lang/dashboard/courses/$courseId/lessons/new': typeof LangDashboardCoursesCourseIdLessonsNewRoute
  '/$lang/student/courses/$courseId/lessons/$lessonId': typeof LangStudentCoursesCourseIdLessonsLessonIdRoute
  '/$lang/dashboard/courses/$courseId/lessons/': typeof LangDashboardCoursesCourseIdLessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/dashboard'
    | '/$lang/student'
    | '/$lang/subscribe'
    | '/$lang/register'
    | '/$lang/'
    | '/$lang/course/$courseSlug'
    | '/$lang/subscribe/checkout'
    | '/$lang/teacher/$teacherSlug'
    | '/$lang/dashboard/'
    | '/$lang/student/'
    | '/$lang/subscribe/'
    | '/$lang/dashboard/courses/new'
    | '/$lang/dashboard/assignments/'
    | '/$lang/dashboard/courses/'
    | '/$lang/dashboard/payments/'
    | '/$lang/dashboard/settings/'
    | '/$lang/dashboard/students/'
    | '/$lang/student/assignments/'
    | '/$lang/student/courses/'
    | '/$lang/student/courses/$courseId/'
    | '/$lang/dashboard/courses/$courseId/lessons/new'
    | '/$lang/student/courses/$courseId/lessons/$lessonId'
    | '/$lang/dashboard/courses/$courseId/lessons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/register'
    | '/$lang'
    | '/$lang/course/$courseSlug'
    | '/$lang/subscribe/checkout'
    | '/$lang/teacher/$teacherSlug'
    | '/$lang/dashboard'
    | '/$lang/student'
    | '/$lang/subscribe'
    | '/$lang/dashboard/courses/new'
    | '/$lang/dashboard/assignments'
    | '/$lang/dashboard/courses'
    | '/$lang/dashboard/payments'
    | '/$lang/dashboard/settings'
    | '/$lang/dashboard/students'
    | '/$lang/student/assignments'
    | '/$lang/student/courses'
    | '/$lang/student/courses/$courseId'
    | '/$lang/dashboard/courses/$courseId/lessons/new'
    | '/$lang/student/courses/$courseId/lessons/$lessonId'
    | '/$lang/dashboard/courses/$courseId/lessons'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/dashboard'
    | '/$lang/student'
    | '/$lang/subscribe'
    | '/$lang/register'
    | '/$lang/'
    | '/$lang/course/$courseSlug'
    | '/$lang/subscribe/checkout'
    | '/$lang/teacher/$teacherSlug'
    | '/$lang/dashboard/'
    | '/$lang/student/'
    | '/$lang/subscribe/'
    | '/$lang/dashboard/courses/new'
    | '/$lang/dashboard/assignments/'
    | '/$lang/dashboard/courses/'
    | '/$lang/dashboard/payments/'
    | '/$lang/dashboard/settings/'
    | '/$lang/dashboard/students/'
    | '/$lang/student/assignments/'
    | '/$lang/student/courses/'
    | '/$lang/student/courses/$courseId/'
    | '/$lang/dashboard/courses/$courseId/lessons/new'
    | '/$lang/student/courses/$courseId/lessons/$lessonId'
    | '/$lang/dashboard/courses/$courseId/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/register': {
      id: '/$lang/register'
      path: '/register'
      fullPath: '/$lang/register'
      preLoaderRoute: typeof LangRegisterRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/subscribe': {
      id: '/$lang/subscribe'
      path: '/subscribe'
      fullPath: '/$lang/subscribe'
      preLoaderRoute: typeof LangSubscribeRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/student': {
      id: '/$lang/student'
      path: '/student'
      fullPath: '/$lang/student'
      preLoaderRoute: typeof LangStudentRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/dashboard': {
      id: '/$lang/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangDashboardRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/subscribe/': {
      id: '/$lang/subscribe/'
      path: '/'
      fullPath: '/$lang/subscribe/'
      preLoaderRoute: typeof LangSubscribeIndexRouteImport
      parentRoute: typeof LangSubscribeRouteRoute
    }
    '/$lang/student/': {
      id: '/$lang/student/'
      path: '/'
      fullPath: '/$lang/student/'
      preLoaderRoute: typeof LangStudentIndexRouteImport
      parentRoute: typeof LangStudentRouteRoute
    }
    '/$lang/dashboard/': {
      id: '/$lang/dashboard/'
      path: '/'
      fullPath: '/$lang/dashboard/'
      preLoaderRoute: typeof LangDashboardIndexRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/teacher/$teacherSlug': {
      id: '/$lang/teacher/$teacherSlug'
      path: '/teacher/$teacherSlug'
      fullPath: '/$lang/teacher/$teacherSlug'
      preLoaderRoute: typeof LangTeacherTeacherSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/subscribe/checkout': {
      id: '/$lang/subscribe/checkout'
      path: '/checkout'
      fullPath: '/$lang/subscribe/checkout'
      preLoaderRoute: typeof LangSubscribeCheckoutRouteImport
      parentRoute: typeof LangSubscribeRouteRoute
    }
    '/$lang/course/$courseSlug': {
      id: '/$lang/course/$courseSlug'
      path: '/course/$courseSlug'
      fullPath: '/$lang/course/$courseSlug'
      preLoaderRoute: typeof LangCourseCourseSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/student/courses/': {
      id: '/$lang/student/courses/'
      path: '/courses'
      fullPath: '/$lang/student/courses/'
      preLoaderRoute: typeof LangStudentCoursesIndexRouteImport
      parentRoute: typeof LangStudentRouteRoute
    }
    '/$lang/student/assignments/': {
      id: '/$lang/student/assignments/'
      path: '/assignments'
      fullPath: '/$lang/student/assignments/'
      preLoaderRoute: typeof LangStudentAssignmentsIndexRouteImport
      parentRoute: typeof LangStudentRouteRoute
    }
    '/$lang/dashboard/students/': {
      id: '/$lang/dashboard/students/'
      path: '/students'
      fullPath: '/$lang/dashboard/students/'
      preLoaderRoute: typeof LangDashboardStudentsIndexRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/dashboard/settings/': {
      id: '/$lang/dashboard/settings/'
      path: '/settings'
      fullPath: '/$lang/dashboard/settings/'
      preLoaderRoute: typeof LangDashboardSettingsIndexRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/dashboard/payments/': {
      id: '/$lang/dashboard/payments/'
      path: '/payments'
      fullPath: '/$lang/dashboard/payments/'
      preLoaderRoute: typeof LangDashboardPaymentsIndexRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/dashboard/courses/': {
      id: '/$lang/dashboard/courses/'
      path: '/courses'
      fullPath: '/$lang/dashboard/courses/'
      preLoaderRoute: typeof LangDashboardCoursesIndexRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/dashboard/assignments/': {
      id: '/$lang/dashboard/assignments/'
      path: '/assignments'
      fullPath: '/$lang/dashboard/assignments/'
      preLoaderRoute: typeof LangDashboardAssignmentsIndexRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/dashboard/courses/new': {
      id: '/$lang/dashboard/courses/new'
      path: '/courses/new'
      fullPath: '/$lang/dashboard/courses/new'
      preLoaderRoute: typeof LangDashboardCoursesNewRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/student/courses/$courseId/': {
      id: '/$lang/student/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/$lang/student/courses/$courseId/'
      preLoaderRoute: typeof LangStudentCoursesCourseIdIndexRouteImport
      parentRoute: typeof LangStudentRouteRoute
    }
    '/$lang/dashboard/courses/$courseId/lessons/': {
      id: '/$lang/dashboard/courses/$courseId/lessons/'
      path: '/courses/$courseId/lessons'
      fullPath: '/$lang/dashboard/courses/$courseId/lessons/'
      preLoaderRoute: typeof LangDashboardCoursesCourseIdLessonsIndexRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/student/courses/$courseId/lessons/$lessonId': {
      id: '/$lang/student/courses/$courseId/lessons/$lessonId'
      path: '/courses/$courseId/lessons/$lessonId'
      fullPath: '/$lang/student/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof LangStudentCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof LangStudentRouteRoute
    }
    '/$lang/dashboard/courses/$courseId/lessons/new': {
      id: '/$lang/dashboard/courses/$courseId/lessons/new'
      path: '/courses/$courseId/lessons/new'
      fullPath: '/$lang/dashboard/courses/$courseId/lessons/new'
      preLoaderRoute: typeof LangDashboardCoursesCourseIdLessonsNewRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
  }
}

interface LangDashboardRouteRouteChildren {
  LangDashboardIndexRoute: typeof LangDashboardIndexRoute
  LangDashboardCoursesNewRoute: typeof LangDashboardCoursesNewRoute
  LangDashboardAssignmentsIndexRoute: typeof LangDashboardAssignmentsIndexRoute
  LangDashboardCoursesIndexRoute: typeof LangDashboardCoursesIndexRoute
  LangDashboardPaymentsIndexRoute: typeof LangDashboardPaymentsIndexRoute
  LangDashboardSettingsIndexRoute: typeof LangDashboardSettingsIndexRoute
  LangDashboardStudentsIndexRoute: typeof LangDashboardStudentsIndexRoute
  LangDashboardCoursesCourseIdLessonsNewRoute: typeof LangDashboardCoursesCourseIdLessonsNewRoute
  LangDashboardCoursesCourseIdLessonsIndexRoute: typeof LangDashboardCoursesCourseIdLessonsIndexRoute
}

const LangDashboardRouteRouteChildren: LangDashboardRouteRouteChildren = {
  LangDashboardIndexRoute: LangDashboardIndexRoute,
  LangDashboardCoursesNewRoute: LangDashboardCoursesNewRoute,
  LangDashboardAssignmentsIndexRoute: LangDashboardAssignmentsIndexRoute,
  LangDashboardCoursesIndexRoute: LangDashboardCoursesIndexRoute,
  LangDashboardPaymentsIndexRoute: LangDashboardPaymentsIndexRoute,
  LangDashboardSettingsIndexRoute: LangDashboardSettingsIndexRoute,
  LangDashboardStudentsIndexRoute: LangDashboardStudentsIndexRoute,
  LangDashboardCoursesCourseIdLessonsNewRoute:
    LangDashboardCoursesCourseIdLessonsNewRoute,
  LangDashboardCoursesCourseIdLessonsIndexRoute:
    LangDashboardCoursesCourseIdLessonsIndexRoute,
}

const LangDashboardRouteRouteWithChildren =
  LangDashboardRouteRoute._addFileChildren(LangDashboardRouteRouteChildren)

interface LangStudentRouteRouteChildren {
  LangStudentIndexRoute: typeof LangStudentIndexRoute
  LangStudentAssignmentsIndexRoute: typeof LangStudentAssignmentsIndexRoute
  LangStudentCoursesIndexRoute: typeof LangStudentCoursesIndexRoute
  LangStudentCoursesCourseIdIndexRoute: typeof LangStudentCoursesCourseIdIndexRoute
  LangStudentCoursesCourseIdLessonsLessonIdRoute: typeof LangStudentCoursesCourseIdLessonsLessonIdRoute
}

const LangStudentRouteRouteChildren: LangStudentRouteRouteChildren = {
  LangStudentIndexRoute: LangStudentIndexRoute,
  LangStudentAssignmentsIndexRoute: LangStudentAssignmentsIndexRoute,
  LangStudentCoursesIndexRoute: LangStudentCoursesIndexRoute,
  LangStudentCoursesCourseIdIndexRoute: LangStudentCoursesCourseIdIndexRoute,
  LangStudentCoursesCourseIdLessonsLessonIdRoute:
    LangStudentCoursesCourseIdLessonsLessonIdRoute,
}

const LangStudentRouteRouteWithChildren =
  LangStudentRouteRoute._addFileChildren(LangStudentRouteRouteChildren)

interface LangSubscribeRouteRouteChildren {
  LangSubscribeCheckoutRoute: typeof LangSubscribeCheckoutRoute
  LangSubscribeIndexRoute: typeof LangSubscribeIndexRoute
}

const LangSubscribeRouteRouteChildren: LangSubscribeRouteRouteChildren = {
  LangSubscribeCheckoutRoute: LangSubscribeCheckoutRoute,
  LangSubscribeIndexRoute: LangSubscribeIndexRoute,
}

const LangSubscribeRouteRouteWithChildren =
  LangSubscribeRouteRoute._addFileChildren(LangSubscribeRouteRouteChildren)

interface LangRouteRouteChildren {
  LangDashboardRouteRoute: typeof LangDashboardRouteRouteWithChildren
  LangStudentRouteRoute: typeof LangStudentRouteRouteWithChildren
  LangSubscribeRouteRoute: typeof LangSubscribeRouteRouteWithChildren
  LangRegisterRoute: typeof LangRegisterRoute
  LangIndexRoute: typeof LangIndexRoute
  LangCourseCourseSlugRoute: typeof LangCourseCourseSlugRoute
  LangTeacherTeacherSlugRoute: typeof LangTeacherTeacherSlugRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangDashboardRouteRoute: LangDashboardRouteRouteWithChildren,
  LangStudentRouteRoute: LangStudentRouteRouteWithChildren,
  LangSubscribeRouteRoute: LangSubscribeRouteRouteWithChildren,
  LangRegisterRoute: LangRegisterRoute,
  LangIndexRoute: LangIndexRoute,
  LangCourseCourseSlugRoute: LangCourseCourseSlugRoute,
  LangTeacherTeacherSlugRoute: LangTeacherTeacherSlugRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
