/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangRegisterRouteImport } from './routes/$lang/register'
import { Route as LangSubscribeRouteRouteImport } from './routes/$lang/subscribe/route'
import { Route as LangStudentRouteRouteImport } from './routes/$lang/student/route'
import { Route as LangDashboardRouteRouteImport } from './routes/$lang/dashboard/route'
import { Route as LangSubscribeIndexRouteImport } from './routes/$lang/subscribe/index'
import { Route as LangStudentIndexRouteImport } from './routes/$lang/student/index'
import { Route as LangDashboardIndexRouteImport } from './routes/$lang/dashboard/index'
import { Route as LangTeacherTeacherSlugRouteImport } from './routes/$lang/teacher/$teacherSlug'
import { Route as LangSubscribeCheckoutRouteImport } from './routes/$lang/subscribe/checkout'
import { Route as LangCourseCourseSlugRouteImport } from './routes/$lang/course/$courseSlug'
import { Route as LangStudentAssignmentsRouteRouteImport } from './routes/$lang/student/assignments/route'
import { Route as LangDashboardStudentsRouteRouteImport } from './routes/$lang/dashboard/students/route'
import { Route as LangDashboardSettingsRouteRouteImport } from './routes/$lang/dashboard/settings/route'
import { Route as LangDashboardAssignmentsRouteRouteImport } from './routes/$lang/dashboard/assignments/route'
import { Route as LangStudentCoursesIndexRouteImport } from './routes/$lang/student/courses/index'
import { Route as LangStudentAssignmentsIndexRouteImport } from './routes/$lang/student/assignments/index'
import { Route as LangDashboardStudentsIndexRouteImport } from './routes/$lang/dashboard/students/index'
import { Route as LangDashboardSettingsIndexRouteImport } from './routes/$lang/dashboard/settings/index'
import { Route as LangDashboardPaymentsIndexRouteImport } from './routes/$lang/dashboard/payments/index'
import { Route as LangDashboardCoursesIndexRouteImport } from './routes/$lang/dashboard/courses/index'
import { Route as LangDashboardBookingIndexRouteImport } from './routes/$lang/dashboard/booking/index'
import { Route as LangDashboardAssignmentsIndexRouteImport } from './routes/$lang/dashboard/assignments/index'
import { Route as LangTeacherTeacherSlugBookRouteImport } from './routes/$lang/teacher/$teacherSlug/book'
import { Route as LangStudentAssignmentsAssignmentIdRouteImport } from './routes/$lang/student/assignments/$assignmentId'
import { Route as LangDashboardStudentsStudentIdRouteImport } from './routes/$lang/dashboard/students/$studentId'
import { Route as LangDashboardSettingsThemeRouteImport } from './routes/$lang/dashboard/settings/theme'
import { Route as LangDashboardSettingsPaymentsRouteImport } from './routes/$lang/dashboard/settings/payments'
import { Route as LangDashboardSettingsNotificationsRouteImport } from './routes/$lang/dashboard/settings/notifications'
import { Route as LangDashboardSettingsIntegrationsRouteImport } from './routes/$lang/dashboard/settings/integrations'
import { Route as LangDashboardSettingsGeneralRouteImport } from './routes/$lang/dashboard/settings/general'
import { Route as LangDashboardSettingsBookingRouteImport } from './routes/$lang/dashboard/settings/booking'
import { Route as LangDashboardSettingsAutomationRouteImport } from './routes/$lang/dashboard/settings/automation'
import { Route as LangDashboardCoursesNewRouteImport } from './routes/$lang/dashboard/courses/new'
import { Route as LangDashboardAssignmentsAssignmentIdRouteImport } from './routes/$lang/dashboard/assignments/$assignmentId'
import { Route as LangStudentCoursesCourseIdIndexRouteImport } from './routes/$lang/student/courses/$courseId/index'
import { Route as LangDashboardCoursesCourseIdLessonsIndexRouteImport } from './routes/$lang/dashboard/courses/$courseId/lessons/index'
import { Route as LangStudentCoursesCourseIdLessonsLessonIdRouteImport } from './routes/$lang/student/courses/$courseId/lessons/$lessonId'
import { Route as LangDashboardCoursesCourseIdLessonsNewRouteImport } from './routes/$lang/dashboard/courses/$courseId/lessons/new'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangRegisterRoute = LangRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSubscribeRouteRoute = LangSubscribeRouteRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangStudentRouteRoute = LangStudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDashboardRouteRoute = LangDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSubscribeIndexRoute = LangSubscribeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangSubscribeRouteRoute,
} as any)
const LangStudentIndexRoute = LangStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangStudentRouteRoute,
} as any)
const LangDashboardIndexRoute = LangDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangDashboardRouteRoute,
} as any)
const LangTeacherTeacherSlugRoute = LangTeacherTeacherSlugRouteImport.update({
  id: '/teacher/$teacherSlug',
  path: '/teacher/$teacherSlug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSubscribeCheckoutRoute = LangSubscribeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LangSubscribeRouteRoute,
} as any)
const LangCourseCourseSlugRoute = LangCourseCourseSlugRouteImport.update({
  id: '/course/$courseSlug',
  path: '/course/$courseSlug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangStudentAssignmentsRouteRoute =
  LangStudentAssignmentsRouteRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => LangStudentRouteRoute,
  } as any)
const LangDashboardStudentsRouteRoute =
  LangDashboardStudentsRouteRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)
const LangDashboardSettingsRouteRoute =
  LangDashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)
const LangDashboardAssignmentsRouteRoute =
  LangDashboardAssignmentsRouteRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)
const LangStudentCoursesIndexRoute = LangStudentCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => LangStudentRouteRoute,
} as any)
const LangStudentAssignmentsIndexRoute =
  LangStudentAssignmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangStudentAssignmentsRouteRoute,
  } as any)
const LangDashboardStudentsIndexRoute =
  LangDashboardStudentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangDashboardStudentsRouteRoute,
  } as any)
const LangDashboardSettingsIndexRoute =
  LangDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangDashboardSettingsRouteRoute,
  } as any)
const LangDashboardPaymentsIndexRoute =
  LangDashboardPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)
const LangDashboardCoursesIndexRoute =
  LangDashboardCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)
const LangDashboardBookingIndexRoute =
  LangDashboardBookingIndexRouteImport.update({
    id: '/booking/',
    path: '/booking/',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)
const LangDashboardAssignmentsIndexRoute =
  LangDashboardAssignmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangDashboardAssignmentsRouteRoute,
  } as any)
const LangTeacherTeacherSlugBookRoute =
  LangTeacherTeacherSlugBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => LangTeacherTeacherSlugRoute,
  } as any)
const LangStudentAssignmentsAssignmentIdRoute =
  LangStudentAssignmentsAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => LangStudentAssignmentsRouteRoute,
  } as any)
const LangDashboardStudentsStudentIdRoute =
  LangDashboardStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => LangDashboardStudentsRouteRoute,
  } as any)
const LangDashboardSettingsThemeRoute =
  LangDashboardSettingsThemeRouteImport.update({
    id: '/theme',
    path: '/theme',
    getParentRoute: () => LangDashboardSettingsRouteRoute,
  } as any)
const LangDashboardSettingsPaymentsRoute =
  LangDashboardSettingsPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => LangDashboardSettingsRouteRoute,
  } as any)
const LangDashboardSettingsNotificationsRoute =
  LangDashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LangDashboardSettingsRouteRoute,
  } as any)
const LangDashboardSettingsIntegrationsRoute =
  LangDashboardSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => LangDashboardSettingsRouteRoute,
  } as any)
const LangDashboardSettingsGeneralRoute =
  LangDashboardSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => LangDashboardSettingsRouteRoute,
  } as any)
const LangDashboardSettingsBookingRoute =
  LangDashboardSettingsBookingRouteImport.update({
    id: '/booking',
    path: '/booking',
    getParentRoute: () => LangDashboardSettingsRouteRoute,
  } as any)
const LangDashboardSettingsAutomationRoute =
  LangDashboardSettingsAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => LangDashboardSettingsRouteRoute,
  } as any)
const LangDashboardCoursesNewRoute = LangDashboardCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => LangDashboardRouteRoute,
} as any)
const LangDashboardAssignmentsAssignmentIdRoute =
  LangDashboardAssignmentsAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => LangDashboardAssignmentsRouteRoute,
  } as any)
const LangStudentCoursesCourseIdIndexRoute =
  LangStudentCoursesCourseIdIndexRouteImport.update({
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => LangStudentRouteRoute,
  } as any)
const LangDashboardCoursesCourseIdLessonsIndexRoute =
  LangDashboardCoursesCourseIdLessonsIndexRouteImport.update({
    id: '/courses/$courseId/lessons/',
    path: '/courses/$courseId/lessons/',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)
const LangStudentCoursesCourseIdLessonsLessonIdRoute =
  LangStudentCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/courses/$courseId/lessons/$lessonId',
    path: '/courses/$courseId/lessons/$lessonId',
    getParentRoute: () => LangStudentRouteRoute,
  } as any)
const LangDashboardCoursesCourseIdLessonsNewRoute =
  LangDashboardCoursesCourseIdLessonsNewRouteImport.update({
    id: '/courses/$courseId/lessons/new',
    path: '/courses/$courseId/lessons/new',
    getParentRoute: () => LangDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/dashboard': typeof LangDashboardRouteRouteWithChildren
  '/$lang/student': typeof LangStudentRouteRouteWithChildren
  '/$lang/subscribe': typeof LangSubscribeRouteRouteWithChildren
  '/$lang/register': typeof LangRegisterRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/dashboard/assignments': typeof LangDashboardAssignmentsRouteRouteWithChildren
  '/$lang/dashboard/settings': typeof LangDashboardSettingsRouteRouteWithChildren
  '/$lang/dashboard/students': typeof LangDashboardStudentsRouteRouteWithChildren
  '/$lang/student/assignments': typeof LangStudentAssignmentsRouteRouteWithChildren
  '/$lang/course/$courseSlug': typeof LangCourseCourseSlugRoute
  '/$lang/subscribe/checkout': typeof LangSubscribeCheckoutRoute
  '/$lang/teacher/$teacherSlug': typeof LangTeacherTeacherSlugRouteWithChildren
  '/$lang/dashboard/': typeof LangDashboardIndexRoute
  '/$lang/student/': typeof LangStudentIndexRoute
  '/$lang/subscribe/': typeof LangSubscribeIndexRoute
  '/$lang/dashboard/assignments/$assignmentId': typeof LangDashboardAssignmentsAssignmentIdRoute
  '/$lang/dashboard/courses/new': typeof LangDashboardCoursesNewRoute
  '/$lang/dashboard/settings/automation': typeof LangDashboardSettingsAutomationRoute
  '/$lang/dashboard/settings/booking': typeof LangDashboardSettingsBookingRoute
  '/$lang/dashboard/settings/general': typeof LangDashboardSettingsGeneralRoute
  '/$lang/dashboard/settings/integrations': typeof LangDashboardSettingsIntegrationsRoute
  '/$lang/dashboard/settings/notifications': typeof LangDashboardSettingsNotificationsRoute
  '/$lang/dashboard/settings/payments': typeof LangDashboardSettingsPaymentsRoute
  '/$lang/dashboard/settings/theme': typeof LangDashboardSettingsThemeRoute
  '/$lang/dashboard/students/$studentId': typeof LangDashboardStudentsStudentIdRoute
  '/$lang/student/assignments/$assignmentId': typeof LangStudentAssignmentsAssignmentIdRoute
  '/$lang/teacher/$teacherSlug/book': typeof LangTeacherTeacherSlugBookRoute
  '/$lang/dashboard/assignments/': typeof LangDashboardAssignmentsIndexRoute
  '/$lang/dashboard/booking/': typeof LangDashboardBookingIndexRoute
  '/$lang/dashboard/courses/': typeof LangDashboardCoursesIndexRoute
  '/$lang/dashboard/payments/': typeof LangDashboardPaymentsIndexRoute
  '/$lang/dashboard/settings/': typeof LangDashboardSettingsIndexRoute
  '/$lang/dashboard/students/': typeof LangDashboardStudentsIndexRoute
  '/$lang/student/assignments/': typeof LangStudentAssignmentsIndexRoute
  '/$lang/student/courses/': typeof LangStudentCoursesIndexRoute
  '/$lang/student/courses/$courseId/': typeof LangStudentCoursesCourseIdIndexRoute
  '/$lang/dashboard/courses/$courseId/lessons/new': typeof LangDashboardCoursesCourseIdLessonsNewRoute
  '/$lang/student/courses/$courseId/lessons/$lessonId': typeof LangStudentCoursesCourseIdLessonsLessonIdRoute
  '/$lang/dashboard/courses/$courseId/lessons/': typeof LangDashboardCoursesCourseIdLessonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/register': typeof LangRegisterRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/course/$courseSlug': typeof LangCourseCourseSlugRoute
  '/$lang/subscribe/checkout': typeof LangSubscribeCheckoutRoute
  '/$lang/teacher/$teacherSlug': typeof LangTeacherTeacherSlugRouteWithChildren
  '/$lang/dashboard': typeof LangDashboardIndexRoute
  '/$lang/student': typeof LangStudentIndexRoute
  '/$lang/subscribe': typeof LangSubscribeIndexRoute
  '/$lang/dashboard/assignments/$assignmentId': typeof LangDashboardAssignmentsAssignmentIdRoute
  '/$lang/dashboard/courses/new': typeof LangDashboardCoursesNewRoute
  '/$lang/dashboard/settings/automation': typeof LangDashboardSettingsAutomationRoute
  '/$lang/dashboard/settings/booking': typeof LangDashboardSettingsBookingRoute
  '/$lang/dashboard/settings/general': typeof LangDashboardSettingsGeneralRoute
  '/$lang/dashboard/settings/integrations': typeof LangDashboardSettingsIntegrationsRoute
  '/$lang/dashboard/settings/notifications': typeof LangDashboardSettingsNotificationsRoute
  '/$lang/dashboard/settings/payments': typeof LangDashboardSettingsPaymentsRoute
  '/$lang/dashboard/settings/theme': typeof LangDashboardSettingsThemeRoute
  '/$lang/dashboard/students/$studentId': typeof LangDashboardStudentsStudentIdRoute
  '/$lang/student/assignments/$assignmentId': typeof LangStudentAssignmentsAssignmentIdRoute
  '/$lang/teacher/$teacherSlug/book': typeof LangTeacherTeacherSlugBookRoute
  '/$lang/dashboard/assignments': typeof LangDashboardAssignmentsIndexRoute
  '/$lang/dashboard/booking': typeof LangDashboardBookingIndexRoute
  '/$lang/dashboard/courses': typeof LangDashboardCoursesIndexRoute
  '/$lang/dashboard/payments': typeof LangDashboardPaymentsIndexRoute
  '/$lang/dashboard/settings': typeof LangDashboardSettingsIndexRoute
  '/$lang/dashboard/students': typeof LangDashboardStudentsIndexRoute
  '/$lang/student/assignments': typeof LangStudentAssignmentsIndexRoute
  '/$lang/student/courses': typeof LangStudentCoursesIndexRoute
  '/$lang/student/courses/$courseId': typeof LangStudentCoursesCourseIdIndexRoute
  '/$lang/dashboard/courses/$courseId/lessons/new': typeof LangDashboardCoursesCourseIdLessonsNewRoute
  '/$lang/student/courses/$courseId/lessons/$lessonId': typeof LangStudentCoursesCourseIdLessonsLessonIdRoute
  '/$lang/dashboard/courses/$courseId/lessons': typeof LangDashboardCoursesCourseIdLessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/dashboard': typeof LangDashboardRouteRouteWithChildren
  '/$lang/student': typeof LangStudentRouteRouteWithChildren
  '/$lang/subscribe': typeof LangSubscribeRouteRouteWithChildren
  '/$lang/register': typeof LangRegisterRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/dashboard/assignments': typeof LangDashboardAssignmentsRouteRouteWithChildren
  '/$lang/dashboard/settings': typeof LangDashboardSettingsRouteRouteWithChildren
  '/$lang/dashboard/students': typeof LangDashboardStudentsRouteRouteWithChildren
  '/$lang/student/assignments': typeof LangStudentAssignmentsRouteRouteWithChildren
  '/$lang/course/$courseSlug': typeof LangCourseCourseSlugRoute
  '/$lang/subscribe/checkout': typeof LangSubscribeCheckoutRoute
  '/$lang/teacher/$teacherSlug': typeof LangTeacherTeacherSlugRouteWithChildren
  '/$lang/dashboard/': typeof LangDashboardIndexRoute
  '/$lang/student/': typeof LangStudentIndexRoute
  '/$lang/subscribe/': typeof LangSubscribeIndexRoute
  '/$lang/dashboard/assignments/$assignmentId': typeof LangDashboardAssignmentsAssignmentIdRoute
  '/$lang/dashboard/courses/new': typeof LangDashboardCoursesNewRoute
  '/$lang/dashboard/settings/automation': typeof LangDashboardSettingsAutomationRoute
  '/$lang/dashboard/settings/booking': typeof LangDashboardSettingsBookingRoute
  '/$lang/dashboard/settings/general': typeof LangDashboardSettingsGeneralRoute
  '/$lang/dashboard/settings/integrations': typeof LangDashboardSettingsIntegrationsRoute
  '/$lang/dashboard/settings/notifications': typeof LangDashboardSettingsNotificationsRoute
  '/$lang/dashboard/settings/payments': typeof LangDashboardSettingsPaymentsRoute
  '/$lang/dashboard/settings/theme': typeof LangDashboardSettingsThemeRoute
  '/$lang/dashboard/students/$studentId': typeof LangDashboardStudentsStudentIdRoute
  '/$lang/student/assignments/$assignmentId': typeof LangStudentAssignmentsAssignmentIdRoute
  '/$lang/teacher/$teacherSlug/book': typeof LangTeacherTeacherSlugBookRoute
  '/$lang/dashboard/assignments/': typeof LangDashboardAssignmentsIndexRoute
  '/$lang/dashboard/booking/': typeof LangDashboardBookingIndexRoute
  '/$lang/dashboard/courses/': typeof LangDashboardCoursesIndexRoute
  '/$lang/dashboard/payments/': typeof LangDashboardPaymentsIndexRoute
  '/$lang/dashboard/settings/': typeof LangDashboardSettingsIndexRoute
  '/$lang/dashboard/students/': typeof LangDashboardStudentsIndexRoute
  '/$lang/student/assignments/': typeof LangStudentAssignmentsIndexRoute
  '/$lang/student/courses/': typeof LangStudentCoursesIndexRoute
  '/$lang/student/courses/$courseId/': typeof LangStudentCoursesCourseIdIndexRoute
  '/$lang/dashboard/courses/$courseId/lessons/new': typeof LangDashboardCoursesCourseIdLessonsNewRoute
  '/$lang/student/courses/$courseId/lessons/$lessonId': typeof LangStudentCoursesCourseIdLessonsLessonIdRoute
  '/$lang/dashboard/courses/$courseId/lessons/': typeof LangDashboardCoursesCourseIdLessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/dashboard'
    | '/$lang/student'
    | '/$lang/subscribe'
    | '/$lang/register'
    | '/$lang/'
    | '/$lang/dashboard/assignments'
    | '/$lang/dashboard/settings'
    | '/$lang/dashboard/students'
    | '/$lang/student/assignments'
    | '/$lang/course/$courseSlug'
    | '/$lang/subscribe/checkout'
    | '/$lang/teacher/$teacherSlug'
    | '/$lang/dashboard/'
    | '/$lang/student/'
    | '/$lang/subscribe/'
    | '/$lang/dashboard/assignments/$assignmentId'
    | '/$lang/dashboard/courses/new'
    | '/$lang/dashboard/settings/automation'
    | '/$lang/dashboard/settings/booking'
    | '/$lang/dashboard/settings/general'
    | '/$lang/dashboard/settings/integrations'
    | '/$lang/dashboard/settings/notifications'
    | '/$lang/dashboard/settings/payments'
    | '/$lang/dashboard/settings/theme'
    | '/$lang/dashboard/students/$studentId'
    | '/$lang/student/assignments/$assignmentId'
    | '/$lang/teacher/$teacherSlug/book'
    | '/$lang/dashboard/assignments/'
    | '/$lang/dashboard/booking/'
    | '/$lang/dashboard/courses/'
    | '/$lang/dashboard/payments/'
    | '/$lang/dashboard/settings/'
    | '/$lang/dashboard/students/'
    | '/$lang/student/assignments/'
    | '/$lang/student/courses/'
    | '/$lang/student/courses/$courseId/'
    | '/$lang/dashboard/courses/$courseId/lessons/new'
    | '/$lang/student/courses/$courseId/lessons/$lessonId'
    | '/$lang/dashboard/courses/$courseId/lessons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/register'
    | '/$lang'
    | '/$lang/course/$courseSlug'
    | '/$lang/subscribe/checkout'
    | '/$lang/teacher/$teacherSlug'
    | '/$lang/dashboard'
    | '/$lang/student'
    | '/$lang/subscribe'
    | '/$lang/dashboard/assignments/$assignmentId'
    | '/$lang/dashboard/courses/new'
    | '/$lang/dashboard/settings/automation'
    | '/$lang/dashboard/settings/booking'
    | '/$lang/dashboard/settings/general'
    | '/$lang/dashboard/settings/integrations'
    | '/$lang/dashboard/settings/notifications'
    | '/$lang/dashboard/settings/payments'
    | '/$lang/dashboard/settings/theme'
    | '/$lang/dashboard/students/$studentId'
    | '/$lang/student/assignments/$assignmentId'
    | '/$lang/teacher/$teacherSlug/book'
    | '/$lang/dashboard/assignments'
    | '/$lang/dashboard/booking'
    | '/$lang/dashboard/courses'
    | '/$lang/dashboard/payments'
    | '/$lang/dashboard/settings'
    | '/$lang/dashboard/students'
    | '/$lang/student/assignments'
    | '/$lang/student/courses'
    | '/$lang/student/courses/$courseId'
    | '/$lang/dashboard/courses/$courseId/lessons/new'
    | '/$lang/student/courses/$courseId/lessons/$lessonId'
    | '/$lang/dashboard/courses/$courseId/lessons'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/dashboard'
    | '/$lang/student'
    | '/$lang/subscribe'
    | '/$lang/register'
    | '/$lang/'
    | '/$lang/dashboard/assignments'
    | '/$lang/dashboard/settings'
    | '/$lang/dashboard/students'
    | '/$lang/student/assignments'
    | '/$lang/course/$courseSlug'
    | '/$lang/subscribe/checkout'
    | '/$lang/teacher/$teacherSlug'
    | '/$lang/dashboard/'
    | '/$lang/student/'
    | '/$lang/subscribe/'
    | '/$lang/dashboard/assignments/$assignmentId'
    | '/$lang/dashboard/courses/new'
    | '/$lang/dashboard/settings/automation'
    | '/$lang/dashboard/settings/booking'
    | '/$lang/dashboard/settings/general'
    | '/$lang/dashboard/settings/integrations'
    | '/$lang/dashboard/settings/notifications'
    | '/$lang/dashboard/settings/payments'
    | '/$lang/dashboard/settings/theme'
    | '/$lang/dashboard/students/$studentId'
    | '/$lang/student/assignments/$assignmentId'
    | '/$lang/teacher/$teacherSlug/book'
    | '/$lang/dashboard/assignments/'
    | '/$lang/dashboard/booking/'
    | '/$lang/dashboard/courses/'
    | '/$lang/dashboard/payments/'
    | '/$lang/dashboard/settings/'
    | '/$lang/dashboard/students/'
    | '/$lang/student/assignments/'
    | '/$lang/student/courses/'
    | '/$lang/student/courses/$courseId/'
    | '/$lang/dashboard/courses/$courseId/lessons/new'
    | '/$lang/student/courses/$courseId/lessons/$lessonId'
    | '/$lang/dashboard/courses/$courseId/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/register': {
      id: '/$lang/register'
      path: '/register'
      fullPath: '/$lang/register'
      preLoaderRoute: typeof LangRegisterRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/subscribe': {
      id: '/$lang/subscribe'
      path: '/subscribe'
      fullPath: '/$lang/subscribe'
      preLoaderRoute: typeof LangSubscribeRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/student': {
      id: '/$lang/student'
      path: '/student'
      fullPath: '/$lang/student'
      preLoaderRoute: typeof LangStudentRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/dashboard': {
      id: '/$lang/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangDashboardRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/subscribe/': {
      id: '/$lang/subscribe/'
      path: '/'
      fullPath: '/$lang/subscribe/'
      preLoaderRoute: typeof LangSubscribeIndexRouteImport
      parentRoute: typeof LangSubscribeRouteRoute
    }
    '/$lang/student/': {
      id: '/$lang/student/'
      path: '/'
      fullPath: '/$lang/student/'
      preLoaderRoute: typeof LangStudentIndexRouteImport
      parentRoute: typeof LangStudentRouteRoute
    }
    '/$lang/dashboard/': {
      id: '/$lang/dashboard/'
      path: '/'
      fullPath: '/$lang/dashboard/'
      preLoaderRoute: typeof LangDashboardIndexRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/teacher/$teacherSlug': {
      id: '/$lang/teacher/$teacherSlug'
      path: '/teacher/$teacherSlug'
      fullPath: '/$lang/teacher/$teacherSlug'
      preLoaderRoute: typeof LangTeacherTeacherSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/subscribe/checkout': {
      id: '/$lang/subscribe/checkout'
      path: '/checkout'
      fullPath: '/$lang/subscribe/checkout'
      preLoaderRoute: typeof LangSubscribeCheckoutRouteImport
      parentRoute: typeof LangSubscribeRouteRoute
    }
    '/$lang/course/$courseSlug': {
      id: '/$lang/course/$courseSlug'
      path: '/course/$courseSlug'
      fullPath: '/$lang/course/$courseSlug'
      preLoaderRoute: typeof LangCourseCourseSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/student/assignments': {
      id: '/$lang/student/assignments'
      path: '/assignments'
      fullPath: '/$lang/student/assignments'
      preLoaderRoute: typeof LangStudentAssignmentsRouteRouteImport
      parentRoute: typeof LangStudentRouteRoute
    }
    '/$lang/dashboard/students': {
      id: '/$lang/dashboard/students'
      path: '/students'
      fullPath: '/$lang/dashboard/students'
      preLoaderRoute: typeof LangDashboardStudentsRouteRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/dashboard/settings': {
      id: '/$lang/dashboard/settings'
      path: '/settings'
      fullPath: '/$lang/dashboard/settings'
      preLoaderRoute: typeof LangDashboardSettingsRouteRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/dashboard/assignments': {
      id: '/$lang/dashboard/assignments'
      path: '/assignments'
      fullPath: '/$lang/dashboard/assignments'
      preLoaderRoute: typeof LangDashboardAssignmentsRouteRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/student/courses/': {
      id: '/$lang/student/courses/'
      path: '/courses'
      fullPath: '/$lang/student/courses/'
      preLoaderRoute: typeof LangStudentCoursesIndexRouteImport
      parentRoute: typeof LangStudentRouteRoute
    }
    '/$lang/student/assignments/': {
      id: '/$lang/student/assignments/'
      path: '/'
      fullPath: '/$lang/student/assignments/'
      preLoaderRoute: typeof LangStudentAssignmentsIndexRouteImport
      parentRoute: typeof LangStudentAssignmentsRouteRoute
    }
    '/$lang/dashboard/students/': {
      id: '/$lang/dashboard/students/'
      path: '/'
      fullPath: '/$lang/dashboard/students/'
      preLoaderRoute: typeof LangDashboardStudentsIndexRouteImport
      parentRoute: typeof LangDashboardStudentsRouteRoute
    }
    '/$lang/dashboard/settings/': {
      id: '/$lang/dashboard/settings/'
      path: '/'
      fullPath: '/$lang/dashboard/settings/'
      preLoaderRoute: typeof LangDashboardSettingsIndexRouteImport
      parentRoute: typeof LangDashboardSettingsRouteRoute
    }
    '/$lang/dashboard/payments/': {
      id: '/$lang/dashboard/payments/'
      path: '/payments'
      fullPath: '/$lang/dashboard/payments/'
      preLoaderRoute: typeof LangDashboardPaymentsIndexRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/dashboard/courses/': {
      id: '/$lang/dashboard/courses/'
      path: '/courses'
      fullPath: '/$lang/dashboard/courses/'
      preLoaderRoute: typeof LangDashboardCoursesIndexRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/dashboard/booking/': {
      id: '/$lang/dashboard/booking/'
      path: '/booking'
      fullPath: '/$lang/dashboard/booking/'
      preLoaderRoute: typeof LangDashboardBookingIndexRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/dashboard/assignments/': {
      id: '/$lang/dashboard/assignments/'
      path: '/'
      fullPath: '/$lang/dashboard/assignments/'
      preLoaderRoute: typeof LangDashboardAssignmentsIndexRouteImport
      parentRoute: typeof LangDashboardAssignmentsRouteRoute
    }
    '/$lang/teacher/$teacherSlug/book': {
      id: '/$lang/teacher/$teacherSlug/book'
      path: '/book'
      fullPath: '/$lang/teacher/$teacherSlug/book'
      preLoaderRoute: typeof LangTeacherTeacherSlugBookRouteImport
      parentRoute: typeof LangTeacherTeacherSlugRoute
    }
    '/$lang/student/assignments/$assignmentId': {
      id: '/$lang/student/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/$lang/student/assignments/$assignmentId'
      preLoaderRoute: typeof LangStudentAssignmentsAssignmentIdRouteImport
      parentRoute: typeof LangStudentAssignmentsRouteRoute
    }
    '/$lang/dashboard/students/$studentId': {
      id: '/$lang/dashboard/students/$studentId'
      path: '/$studentId'
      fullPath: '/$lang/dashboard/students/$studentId'
      preLoaderRoute: typeof LangDashboardStudentsStudentIdRouteImport
      parentRoute: typeof LangDashboardStudentsRouteRoute
    }
    '/$lang/dashboard/settings/theme': {
      id: '/$lang/dashboard/settings/theme'
      path: '/theme'
      fullPath: '/$lang/dashboard/settings/theme'
      preLoaderRoute: typeof LangDashboardSettingsThemeRouteImport
      parentRoute: typeof LangDashboardSettingsRouteRoute
    }
    '/$lang/dashboard/settings/payments': {
      id: '/$lang/dashboard/settings/payments'
      path: '/payments'
      fullPath: '/$lang/dashboard/settings/payments'
      preLoaderRoute: typeof LangDashboardSettingsPaymentsRouteImport
      parentRoute: typeof LangDashboardSettingsRouteRoute
    }
    '/$lang/dashboard/settings/notifications': {
      id: '/$lang/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/$lang/dashboard/settings/notifications'
      preLoaderRoute: typeof LangDashboardSettingsNotificationsRouteImport
      parentRoute: typeof LangDashboardSettingsRouteRoute
    }
    '/$lang/dashboard/settings/integrations': {
      id: '/$lang/dashboard/settings/integrations'
      path: '/integrations'
      fullPath: '/$lang/dashboard/settings/integrations'
      preLoaderRoute: typeof LangDashboardSettingsIntegrationsRouteImport
      parentRoute: typeof LangDashboardSettingsRouteRoute
    }
    '/$lang/dashboard/settings/general': {
      id: '/$lang/dashboard/settings/general'
      path: '/general'
      fullPath: '/$lang/dashboard/settings/general'
      preLoaderRoute: typeof LangDashboardSettingsGeneralRouteImport
      parentRoute: typeof LangDashboardSettingsRouteRoute
    }
    '/$lang/dashboard/settings/booking': {
      id: '/$lang/dashboard/settings/booking'
      path: '/booking'
      fullPath: '/$lang/dashboard/settings/booking'
      preLoaderRoute: typeof LangDashboardSettingsBookingRouteImport
      parentRoute: typeof LangDashboardSettingsRouteRoute
    }
    '/$lang/dashboard/settings/automation': {
      id: '/$lang/dashboard/settings/automation'
      path: '/automation'
      fullPath: '/$lang/dashboard/settings/automation'
      preLoaderRoute: typeof LangDashboardSettingsAutomationRouteImport
      parentRoute: typeof LangDashboardSettingsRouteRoute
    }
    '/$lang/dashboard/courses/new': {
      id: '/$lang/dashboard/courses/new'
      path: '/courses/new'
      fullPath: '/$lang/dashboard/courses/new'
      preLoaderRoute: typeof LangDashboardCoursesNewRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/dashboard/assignments/$assignmentId': {
      id: '/$lang/dashboard/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/$lang/dashboard/assignments/$assignmentId'
      preLoaderRoute: typeof LangDashboardAssignmentsAssignmentIdRouteImport
      parentRoute: typeof LangDashboardAssignmentsRouteRoute
    }
    '/$lang/student/courses/$courseId/': {
      id: '/$lang/student/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/$lang/student/courses/$courseId/'
      preLoaderRoute: typeof LangStudentCoursesCourseIdIndexRouteImport
      parentRoute: typeof LangStudentRouteRoute
    }
    '/$lang/dashboard/courses/$courseId/lessons/': {
      id: '/$lang/dashboard/courses/$courseId/lessons/'
      path: '/courses/$courseId/lessons'
      fullPath: '/$lang/dashboard/courses/$courseId/lessons/'
      preLoaderRoute: typeof LangDashboardCoursesCourseIdLessonsIndexRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
    '/$lang/student/courses/$courseId/lessons/$lessonId': {
      id: '/$lang/student/courses/$courseId/lessons/$lessonId'
      path: '/courses/$courseId/lessons/$lessonId'
      fullPath: '/$lang/student/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof LangStudentCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof LangStudentRouteRoute
    }
    '/$lang/dashboard/courses/$courseId/lessons/new': {
      id: '/$lang/dashboard/courses/$courseId/lessons/new'
      path: '/courses/$courseId/lessons/new'
      fullPath: '/$lang/dashboard/courses/$courseId/lessons/new'
      preLoaderRoute: typeof LangDashboardCoursesCourseIdLessonsNewRouteImport
      parentRoute: typeof LangDashboardRouteRoute
    }
  }
}

interface LangDashboardAssignmentsRouteRouteChildren {
  LangDashboardAssignmentsAssignmentIdRoute: typeof LangDashboardAssignmentsAssignmentIdRoute
  LangDashboardAssignmentsIndexRoute: typeof LangDashboardAssignmentsIndexRoute
}

const LangDashboardAssignmentsRouteRouteChildren: LangDashboardAssignmentsRouteRouteChildren =
  {
    LangDashboardAssignmentsAssignmentIdRoute:
      LangDashboardAssignmentsAssignmentIdRoute,
    LangDashboardAssignmentsIndexRoute: LangDashboardAssignmentsIndexRoute,
  }

const LangDashboardAssignmentsRouteRouteWithChildren =
  LangDashboardAssignmentsRouteRoute._addFileChildren(
    LangDashboardAssignmentsRouteRouteChildren,
  )

interface LangDashboardSettingsRouteRouteChildren {
  LangDashboardSettingsAutomationRoute: typeof LangDashboardSettingsAutomationRoute
  LangDashboardSettingsBookingRoute: typeof LangDashboardSettingsBookingRoute
  LangDashboardSettingsGeneralRoute: typeof LangDashboardSettingsGeneralRoute
  LangDashboardSettingsIntegrationsRoute: typeof LangDashboardSettingsIntegrationsRoute
  LangDashboardSettingsNotificationsRoute: typeof LangDashboardSettingsNotificationsRoute
  LangDashboardSettingsPaymentsRoute: typeof LangDashboardSettingsPaymentsRoute
  LangDashboardSettingsThemeRoute: typeof LangDashboardSettingsThemeRoute
  LangDashboardSettingsIndexRoute: typeof LangDashboardSettingsIndexRoute
}

const LangDashboardSettingsRouteRouteChildren: LangDashboardSettingsRouteRouteChildren =
  {
    LangDashboardSettingsAutomationRoute: LangDashboardSettingsAutomationRoute,
    LangDashboardSettingsBookingRoute: LangDashboardSettingsBookingRoute,
    LangDashboardSettingsGeneralRoute: LangDashboardSettingsGeneralRoute,
    LangDashboardSettingsIntegrationsRoute:
      LangDashboardSettingsIntegrationsRoute,
    LangDashboardSettingsNotificationsRoute:
      LangDashboardSettingsNotificationsRoute,
    LangDashboardSettingsPaymentsRoute: LangDashboardSettingsPaymentsRoute,
    LangDashboardSettingsThemeRoute: LangDashboardSettingsThemeRoute,
    LangDashboardSettingsIndexRoute: LangDashboardSettingsIndexRoute,
  }

const LangDashboardSettingsRouteRouteWithChildren =
  LangDashboardSettingsRouteRoute._addFileChildren(
    LangDashboardSettingsRouteRouteChildren,
  )

interface LangDashboardStudentsRouteRouteChildren {
  LangDashboardStudentsStudentIdRoute: typeof LangDashboardStudentsStudentIdRoute
  LangDashboardStudentsIndexRoute: typeof LangDashboardStudentsIndexRoute
}

const LangDashboardStudentsRouteRouteChildren: LangDashboardStudentsRouteRouteChildren =
  {
    LangDashboardStudentsStudentIdRoute: LangDashboardStudentsStudentIdRoute,
    LangDashboardStudentsIndexRoute: LangDashboardStudentsIndexRoute,
  }

const LangDashboardStudentsRouteRouteWithChildren =
  LangDashboardStudentsRouteRoute._addFileChildren(
    LangDashboardStudentsRouteRouteChildren,
  )

interface LangDashboardRouteRouteChildren {
  LangDashboardAssignmentsRouteRoute: typeof LangDashboardAssignmentsRouteRouteWithChildren
  LangDashboardSettingsRouteRoute: typeof LangDashboardSettingsRouteRouteWithChildren
  LangDashboardStudentsRouteRoute: typeof LangDashboardStudentsRouteRouteWithChildren
  LangDashboardIndexRoute: typeof LangDashboardIndexRoute
  LangDashboardCoursesNewRoute: typeof LangDashboardCoursesNewRoute
  LangDashboardBookingIndexRoute: typeof LangDashboardBookingIndexRoute
  LangDashboardCoursesIndexRoute: typeof LangDashboardCoursesIndexRoute
  LangDashboardPaymentsIndexRoute: typeof LangDashboardPaymentsIndexRoute
  LangDashboardCoursesCourseIdLessonsNewRoute: typeof LangDashboardCoursesCourseIdLessonsNewRoute
  LangDashboardCoursesCourseIdLessonsIndexRoute: typeof LangDashboardCoursesCourseIdLessonsIndexRoute
}

const LangDashboardRouteRouteChildren: LangDashboardRouteRouteChildren = {
  LangDashboardAssignmentsRouteRoute:
    LangDashboardAssignmentsRouteRouteWithChildren,
  LangDashboardSettingsRouteRoute: LangDashboardSettingsRouteRouteWithChildren,
  LangDashboardStudentsRouteRoute: LangDashboardStudentsRouteRouteWithChildren,
  LangDashboardIndexRoute: LangDashboardIndexRoute,
  LangDashboardCoursesNewRoute: LangDashboardCoursesNewRoute,
  LangDashboardBookingIndexRoute: LangDashboardBookingIndexRoute,
  LangDashboardCoursesIndexRoute: LangDashboardCoursesIndexRoute,
  LangDashboardPaymentsIndexRoute: LangDashboardPaymentsIndexRoute,
  LangDashboardCoursesCourseIdLessonsNewRoute:
    LangDashboardCoursesCourseIdLessonsNewRoute,
  LangDashboardCoursesCourseIdLessonsIndexRoute:
    LangDashboardCoursesCourseIdLessonsIndexRoute,
}

const LangDashboardRouteRouteWithChildren =
  LangDashboardRouteRoute._addFileChildren(LangDashboardRouteRouteChildren)

interface LangStudentAssignmentsRouteRouteChildren {
  LangStudentAssignmentsAssignmentIdRoute: typeof LangStudentAssignmentsAssignmentIdRoute
  LangStudentAssignmentsIndexRoute: typeof LangStudentAssignmentsIndexRoute
}

const LangStudentAssignmentsRouteRouteChildren: LangStudentAssignmentsRouteRouteChildren =
  {
    LangStudentAssignmentsAssignmentIdRoute:
      LangStudentAssignmentsAssignmentIdRoute,
    LangStudentAssignmentsIndexRoute: LangStudentAssignmentsIndexRoute,
  }

const LangStudentAssignmentsRouteRouteWithChildren =
  LangStudentAssignmentsRouteRoute._addFileChildren(
    LangStudentAssignmentsRouteRouteChildren,
  )

interface LangStudentRouteRouteChildren {
  LangStudentAssignmentsRouteRoute: typeof LangStudentAssignmentsRouteRouteWithChildren
  LangStudentIndexRoute: typeof LangStudentIndexRoute
  LangStudentCoursesIndexRoute: typeof LangStudentCoursesIndexRoute
  LangStudentCoursesCourseIdIndexRoute: typeof LangStudentCoursesCourseIdIndexRoute
  LangStudentCoursesCourseIdLessonsLessonIdRoute: typeof LangStudentCoursesCourseIdLessonsLessonIdRoute
}

const LangStudentRouteRouteChildren: LangStudentRouteRouteChildren = {
  LangStudentAssignmentsRouteRoute:
    LangStudentAssignmentsRouteRouteWithChildren,
  LangStudentIndexRoute: LangStudentIndexRoute,
  LangStudentCoursesIndexRoute: LangStudentCoursesIndexRoute,
  LangStudentCoursesCourseIdIndexRoute: LangStudentCoursesCourseIdIndexRoute,
  LangStudentCoursesCourseIdLessonsLessonIdRoute:
    LangStudentCoursesCourseIdLessonsLessonIdRoute,
}

const LangStudentRouteRouteWithChildren =
  LangStudentRouteRoute._addFileChildren(LangStudentRouteRouteChildren)

interface LangSubscribeRouteRouteChildren {
  LangSubscribeCheckoutRoute: typeof LangSubscribeCheckoutRoute
  LangSubscribeIndexRoute: typeof LangSubscribeIndexRoute
}

const LangSubscribeRouteRouteChildren: LangSubscribeRouteRouteChildren = {
  LangSubscribeCheckoutRoute: LangSubscribeCheckoutRoute,
  LangSubscribeIndexRoute: LangSubscribeIndexRoute,
}

const LangSubscribeRouteRouteWithChildren =
  LangSubscribeRouteRoute._addFileChildren(LangSubscribeRouteRouteChildren)

interface LangTeacherTeacherSlugRouteChildren {
  LangTeacherTeacherSlugBookRoute: typeof LangTeacherTeacherSlugBookRoute
}

const LangTeacherTeacherSlugRouteChildren: LangTeacherTeacherSlugRouteChildren =
  {
    LangTeacherTeacherSlugBookRoute: LangTeacherTeacherSlugBookRoute,
  }

const LangTeacherTeacherSlugRouteWithChildren =
  LangTeacherTeacherSlugRoute._addFileChildren(
    LangTeacherTeacherSlugRouteChildren,
  )

interface LangRouteRouteChildren {
  LangDashboardRouteRoute: typeof LangDashboardRouteRouteWithChildren
  LangStudentRouteRoute: typeof LangStudentRouteRouteWithChildren
  LangSubscribeRouteRoute: typeof LangSubscribeRouteRouteWithChildren
  LangRegisterRoute: typeof LangRegisterRoute
  LangIndexRoute: typeof LangIndexRoute
  LangCourseCourseSlugRoute: typeof LangCourseCourseSlugRoute
  LangTeacherTeacherSlugRoute: typeof LangTeacherTeacherSlugRouteWithChildren
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangDashboardRouteRoute: LangDashboardRouteRouteWithChildren,
  LangStudentRouteRoute: LangStudentRouteRouteWithChildren,
  LangSubscribeRouteRoute: LangSubscribeRouteRouteWithChildren,
  LangRegisterRoute: LangRegisterRoute,
  LangIndexRoute: LangIndexRoute,
  LangCourseCourseSlugRoute: LangCourseCourseSlugRoute,
  LangTeacherTeacherSlugRoute: LangTeacherTeacherSlugRouteWithChildren,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
